package org.example.expensecommand.api;

import org.example.expensecommand.mapper.ApiToDomainMapper;
import org.example.expensecommand.dto.CreateExpenseRequestDto;
import org.example.expensecommand.dto.TransactionResult;
import org.example.expensecommand.service.ExpenseCommandService;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

// The following imports refer to classes generated by OpenAPI generator
// They will be available after the first Maven build with 'mvn clean generate-sources'
// import org.example.expensecommand.api.generated.ExpensesApi;
// import org.example.expensecommand.model.CreateExpenseRequest;
// import org.example.expensecommand.model.TransactionResponse;

@Service
public class ExpensesApiDelegateImpl {
    // Temporarily disabled - will implement ExpensesApi after OpenAPI generation
    // public class ExpensesApiDelegateImpl implements ExpensesApi {

    private final ApiToDomainMapper mapper;
    private final ExpenseCommandService expenseCommandService;

    public ExpensesApiDelegateImpl(ApiToDomainMapper mapper,
                                   ExpenseCommandService expenseCommandService) {
        this.mapper = mapper;
        this.expenseCommandService = expenseCommandService;
    }

    // This method signature will match the generated ExpensesApi interface after OpenAPI generation
    // For now, we provide the implementation that will be used by the delegate
    public ResponseEntity<?> createExpense(Object createExpenseRequest) {
        // Cast will work after OpenAPI generation provides the model classes
        if (createExpenseRequest == null) {
            return ResponseEntity.badRequest().build();
        }

        CreateExpenseRequestDto dto = mapper.toDto(createExpenseRequest);
        TransactionResult result = expenseCommandService.createExpense(dto);

        // Will return proper model after OpenAPI generation
        return ResponseEntity.status(201).body(result);
    }
}