spring:
  application:
    name: expense-command-service
    version: 1.0.0

  profiles:
    active: dev
    include: dev

  # Default datasource configuration (will be overridden by profile)
  datasource:
    url: jdbc:postgresql://localhost:5432/pgsvc
    username: pgsvc
    password: pgsvc@123

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8082
